image: gradle:7.5-jdk17

stages:
  - check

variables:
  GRADLE_OPTS: -Dorg.gradle.caching=true
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

check-job:
  stage: check
  script: 
    - gradle check
  services:
  - name: docker:20.10.16-dind
    alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
  only:
    - merge_requests
  artifacts:
    when: always
    reports:
      junit: '**/test-results/**/TEST-*.xml'
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
