spring:
  application:
    name: jmm
  datasource:
    url: jdbc:tc:postgresql:11:///test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: always
    include-message: always

logging:
  level:
    root: info

# Spring Boot Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: 'info, health, metrics, prometheus, heapdump, scheduledtasks, logfile, loggers, mappings'
  info:
    git.mode: full
  endpoint:
    health:
      show-details: always